#!/usr/bin/env python3
"""Install WorkOrder Git hooks (pre-commit version bump)."""

import subprocess
import sys
from pathlib import Path


class HooksInstaller:
    def __init__(self):
        try:
            self.project_root = Path(
                subprocess.check_output(
                    ["git", "rev-parse", "--show-toplevel"]
                )
                .decode()
                .strip()
            )
            self.git_dir = Path(
                subprocess.check_output(["git", "rev-parse", "--git-dir"])
                .decode()
                .strip()
            )
        except Exception as e:
            print(f"Error: Could not determine git repository: {e}")
            sys.exit(1)
        self.hooks_dir = Path(__file__).parent
        self.git_hooks_dir = self.git_dir / "hooks"

    def check_requirements(self):
        print("Checking requirements...")
        if not (self.project_root / ".git").exists():
            print("  FAIL Not in a Git repository")
            return False
        if sys.version_info < (3, 6):
            print("  FAIL Python 3.6+ required")
            return False
        print(f"  OK Python {sys.version.split()[0]}")
        print(f"  OK Project root: {self.project_root}")
        return True

    def _get_find_python_shell(self):
        return """find_python() {
    if command -v python3 >/dev/null 2>&1; then
        if python3 -c "import sys" 2>/dev/null; then
            echo "python3"
            return
        fi
    fi
    if command -v python >/dev/null 2>&1; then
        if python -c "import sys" 2>/dev/null; then
            echo "python"
            return
        fi
    fi
    return 1
}
"""

    def create_main_hooks(self):
        print("Creating Git hooks...")
        find_python = self._get_find_python_shell()
        hooks_dir_abs = str(self.hooks_dir.resolve())
        find_root = f"""PROJECT_ROOT="{hooks_dir_abs}/../.."
PROJECT_ROOT="$(cd "$PROJECT_ROOT" && pwd)"
if [ -n "$GIT_WORK_TREE" ] && [ -d "$GIT_WORK_TREE/utils/hooks" ]; then
    PROJECT_ROOT="$GIT_WORK_TREE"
fi
"""

        pre_commit_content = f"""#!/bin/sh
# Pre-commit hook wrapper - generated by utils/hooks/install.py

{find_python}
{find_root}
PYTHON=$(find_python)
if [ -z "$PYTHON" ]; then
    echo "Error: Python not found. Install Python 3.6+ and add to PATH."
    exit 1
fi

exec "$PYTHON" "$PROJECT_ROOT/utils/hooks/pre_commit.py"
"""

        self.git_hooks_dir.mkdir(parents=True, exist_ok=True)
        pre_commit_file = self.git_hooks_dir / "pre-commit"
        pre_commit_file.write_bytes(
            pre_commit_content.encode("utf-8").replace(b"\r\n", b"\n")
        )
        try:
            pre_commit_file.chmod(0o755)
        except OSError:
            pass
        print("  Created .git/hooks/pre-commit")

    def install(self):
        print("Installing WorkOrder Git hooks...")
        print("=" * 60)
        if not self.check_requirements():
            return False
        self.create_main_hooks()
        print("\n" + "=" * 60)
        print("Git hooks installed successfully!")
        print("\nActive hooks:")
        print("  version/update_version.py - bump VERSION_PATCH on each commit")
        print("\nInstall again anytime with:")
        print("  python3 utils/hooks/install.py")
        print("  or: bash utils/hooks/setup-hooks.sh")
        return True


def main():
    installer = HooksInstaller()
    return 0 if installer.install() else 1


if __name__ == "__main__":
    sys.exit(main())
