; WorkOrder Windows installer (NSIS).
; Defines come from nsis.defines.nsh (generated by pack.ps1).

!include "MUI2.nsh"
!include "x64.nsh"
!include "nsis.defines.nsh"

Unicode true

Name "${APP_NAME}"
OutFile "${OUT_FILE}"
BrandingText "${APP_NAME}"
InstallDir "$PROGRAMFILES64\${APP_NAME}"
RequestExecutionLevel admin

!define MUI_ICON "app_icon.ico"
!define MUI_UNICON "app_icon.ico"
!define MUI_FINISHPAGE_RUN "$INSTDIR\WorkOrder.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Run ${APP_NAME}"

VIProductVersion "${APP_VERSION}"
VIAddVersionKey "ProductName" "${APP_NAME}"
VIAddVersionKey "CompanyName" "${PUBLISHER}"
VIAddVersionKey "FileDescription" "${APP_NAME}"
VIAddVersionKey "FileVersion" "${DAP_VER}"
VIAddVersionKey "ProductVersion" "${DAP_VER}"

Function .onInit
	${If} ${RunningX64}
		SetRegView 64
	${Else}
		MessageBox MB_OK "${APP_NAME} supports x64 only"
		Abort
	${EndIf}
FunctionEnd

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Russian"

Section "${APP_NAME}" SEC_CORE
	SectionIn RO
	SetOutPath "$INSTDIR"

	ExecWait 'taskkill /F /IM WorkOrder.exe'

	; Portable Qt tree produced by windeployqt
	File /r "payload\*.*"

	CreateDirectory "$SMPROGRAMS\${APP_NAME}"
	CreateShortCut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\WorkOrder.exe"
	CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\WorkOrder.exe"
	CreateShortCut "$SMPROGRAMS\${APP_NAME}\Uninstall.lnk" "$INSTDIR\uninstall.exe"

	WriteUninstaller "$INSTDIR\uninstall.exe"
	WriteRegStr HKLM "${UNINSTALL_PATH}" "DisplayName" "${APP_NAME}"
	WriteRegStr HKLM "${UNINSTALL_PATH}" "DisplayVersion" "${DAP_VER}"
	WriteRegStr HKLM "${UNINSTALL_PATH}" "Publisher" "${PUBLISHER}"
	WriteRegStr HKLM "${UNINSTALL_PATH}" "InstallLocation" "$INSTDIR"
	WriteRegStr HKLM "${UNINSTALL_PATH}" "DisplayIcon" "$INSTDIR\WorkOrder.exe"
	WriteRegStr HKLM "${UNINSTALL_PATH}" "UninstallString" "$INSTDIR\uninstall.exe"
SectionEnd

Section "Uninstall"
	ExecWait 'taskkill /F /IM WorkOrder.exe'
	Delete "$DESKTOP\${APP_NAME}.lnk"
	RMDir /r "$SMPROGRAMS\${APP_NAME}"
	RMDir /r "$INSTDIR"
	DeleteRegKey HKLM "${UNINSTALL_PATH}"
SectionEnd
