# Pack WorkOrder for Windows: windeployqt + NSIS installer.
# Requires a prior build.ps1 run (dist\WorkOrder.exe) and NSIS (makensis).
#
# Usage:
#   .\prod_build\windows\pack.ps1
#   .\prod_build\windows\pack.ps1 -Version 1.0.9
#   .\prod_build\windows\pack.ps1 -AlsoZip
#
# Output:
#   prod_build\windows\WorkOrder\                              (portable tree)
#   prod_build\windows\WorkOrder-desktop-<version>-setup.exe   (installer)
#   optional zip if -AlsoZip

param(
    [string]$Version = "",
    [string]$QtRoot = "",
    [string]$MingwBin = "",
    [switch]$AlsoZip
)

$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "_common.ps1")

$DistDir = Join-Path $script:WoWindowsDir "dist"
$AppDir = Join-Path $script:WoWindowsDir "WorkOrder"
$NsisDir = Join-Path $script:WoWindowsDir "nsis"
$PayloadDir = Join-Path $NsisDir "payload"
$QmlDir = Join-Path $script:WoProjectRoot "resources\qml"
$DistExe = Join-Path $DistDir "WorkOrder.exe"
$EnvFile = Join-Path $script:WoWindowsDir "build.env.ps1"
$IconSrc = Join-Path $script:WoProjectRoot "resources\icons\appIcons\icon_win32.ico"
$NsiSrc = Join-Path $script:WoWindowsDir "build.nsi"

function Resolve-Makensis {
    $cmd = Get-Command makensis.exe -ErrorAction SilentlyContinue
    if($cmd)
    {
        return $cmd.Source
    }
    $candidates = @(
        "${env:ProgramFiles}\NSIS\makensis.exe",
        "${env:ProgramFiles(x86)}\NSIS\makensis.exe",
        "C:\NSIS\makensis.exe"
    )
    foreach($candidate in $candidates)
    {
        if(Test-Path $candidate)
        {
            return $candidate
        }
    }
    throw @"
NSIS (makensis.exe) not found.
Install NSIS from https://nsis.sourceforge.io/Download
or: winget install NSIS.NSIS
Then re-run pack.ps1
"@
}

if(-not (Test-Path $DistExe))
{
    throw "No build found: $DistExe`nRun .\prod_build\windows\build.ps1 first"
}
if(-not (Test-Path $NsiSrc))
{
    throw "NSIS script not found: $NsiSrc"
}

if(Test-Path $EnvFile)
{
    . $EnvFile
}

if([string]::IsNullOrWhiteSpace($Version))
{
    $Version = Read-ProjectVersion
}

if([string]::IsNullOrWhiteSpace($QtRoot))
{
    $QtRoot = $env:WORKORDER_QT_ROOT
}
if([string]::IsNullOrWhiteSpace($MingwBin))
{
    $MingwBin = $env:WORKORDER_MINGW_BIN
}

$QtRoot = Resolve-QtRoot -Preferred $QtRoot
$MingwBin = Resolve-MingwBin -Preferred $MingwBin
$Makensis = Resolve-Makensis
$WinDeployQt = Join-Path $QtRoot "bin\windeployqt.exe"
$BuildType = if($env:WORKORDER_BUILD_TYPE) { $env:WORKORDER_BUILD_TYPE } else { "release" }
$DeployRelease = if($BuildType -eq "debug") { "--debug" } else { "--release" }

$SetupName = "WorkOrder-desktop-$Version-setup.exe"
$SetupPath = Join-Path $script:WoWindowsDir $SetupName
$ZipName = "WorkOrder-desktop-$Version-windows.zip"
$ZipPath = Join-Path $script:WoWindowsDir $ZipName

$env:PATH = "$MingwBin;$(Join-Path $QtRoot 'bin');$env:PATH"

Write-Host "==> Qt:       $QtRoot"
Write-Host "==> MinGW:    $MingwBin"
Write-Host "==> NSIS:     $Makensis"
Write-Host "==> Version:  $Version"
Write-Host "==> Dist:     $DistExe"

$running = Get-Process -Name "WorkOrder" -ErrorAction SilentlyContinue
if($running)
{
    Write-Host "==> Stopping running WorkOrder.exe"
    $running | Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep -Milliseconds 500
}

Write-Host "==> Stage portable folder"
if(Test-Path $AppDir)
{
    Remove-Item -Recurse -Force $AppDir
}
New-Item -ItemType Directory -Force -Path $AppDir | Out-Null
Copy-Item $DistExe (Join-Path $AppDir "WorkOrder.exe")

Write-Host "==> windeployqt"
& $WinDeployQt `
    $DeployRelease `
    --compiler-runtime `
    --qmldir $QmlDir `
    --no-translations `
    (Join-Path $AppDir "WorkOrder.exe")
if($LASTEXITCODE -ne 0)
{
    throw "windeployqt failed"
}

$runtimeDlls = @(
    "libgcc_s_seh-1.dll",
    "libstdc++-6.dll",
    "libwinpthread-1.dll"
)
foreach($dll in $runtimeDlls)
{
    $src = Join-Path $MingwBin $dll
    if(Test-Path $src)
    {
        Copy-Item $src (Join-Path $AppDir $dll) -Force
    }
}

Get-ChildItem -Path $AppDir -Recurse -Filter "*.qmltypes" -ErrorAction SilentlyContinue |
    Remove-Item -Force -ErrorAction SilentlyContinue

Write-Host "==> Prepare NSIS staging"
if(Test-Path $NsisDir)
{
    Remove-Item -Recurse -Force $NsisDir
}
New-Item -ItemType Directory -Force -Path $PayloadDir | Out-Null
Copy-Item -Path (Join-Path $AppDir "*") -Destination $PayloadDir -Recurse -Force
Copy-Item $NsiSrc (Join-Path $NsisDir "build.nsi")
if(Test-Path $IconSrc)
{
    Copy-Item $IconSrc (Join-Path $NsisDir "app_icon.ico")
}
else
{
    throw "App icon not found: $IconSrc"
}

$definesPath = Join-Path $NsisDir "nsis.defines.nsh"
@"
; Auto-generated by pack.ps1
!define APP_NAME "WorkOrder"
!define PUBLISHER "WorkOrder"
!define DAP_VER "$Version"
!define APP_VERSION "$Version.0"
!define OUT_FILE "$SetupName"
!define UNINSTALL_PATH "Software\Microsoft\Windows\CurrentVersion\Uninstall\WorkOrder"
"@ | Set-Content -Encoding ASCII $definesPath

Write-Host "==> makensis"
Push-Location $NsisDir
try
{
    & $Makensis "build.nsi"
    if($LASTEXITCODE -ne 0)
    {
        throw "makensis failed with code $LASTEXITCODE"
    }
}
finally
{
    Pop-Location
}

$BuiltSetup = Join-Path $NsisDir $SetupName
if(-not (Test-Path $BuiltSetup))
{
    throw "Installer was not created: $BuiltSetup"
}
Copy-Item $BuiltSetup $SetupPath -Force

if($AlsoZip)
{
    Write-Host "==> Creating zip archive (-AlsoZip)"
    if(Test-Path $ZipPath)
    {
        Remove-Item -Force $ZipPath
    }
    $parent = Split-Path -Parent $AppDir
    $leaf = Split-Path -Leaf $AppDir
    Push-Location $parent
    try
    {
        & tar.exe -a -cf $ZipPath $leaf
        if($LASTEXITCODE -ne 0)
        {
            throw "tar zip failed"
        }
    }
    finally
    {
        Pop-Location
    }
}

Write-Host "==> Pack done"
Write-Host "App:       $AppDir"
Write-Host "Installer: $SetupPath"
if($AlsoZip)
{
    Write-Host "Zip:       $ZipPath"
}
Write-Host "Run the setup.exe on the target PC to install WorkOrder"
