if(NOT DEFINED WORKORDER_ROOT)
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/src/main.py")
        set(WORKORDER_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
    elseif(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/../src/main.py")
        get_filename_component(WORKORDER_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/.." ABSOLUTE)
    else()
        get_filename_component(WORKORDER_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/.." ABSOLUTE)
    endif()
    get_filename_component(WORKORDER_ROOT "${WORKORDER_ROOT}" ABSOLUTE)
endif()
